export const TOPICS = [
  {
    id: "verb-forms",
    label: "Verb Tenses & Forms",
    subtopics: [
      "Simple Present",
      "Simple Past",
      "Present Perfect",
      "Past Perfect",
      "Future (will / going to)",
      "Present Continuous",
      "Past Continuous",
      "Past Perfect Continuous",
      "Future Perfect",
      "Gerund vs Infinitive",
      "Regular Verbs",
      "Irregular Verbs",
    ],
  },
  {
    id: "voice-modals-imperative",
    label: "Voice, Modals & Imperatives",
    subtopics: [
      "Active vs Passive Voice",
      "Present passive",
      "Past passive",
      "Perfect passive",
      "Passive with modals",
      "Causative have/get",
      "can / could",
      "may / might",
      "must / have to",
      "should / ought to",
      "will / would",
      "need / dare",
      "Imperative sentences",
    ],
  },
  {
    id: "conditionals-speech",
    label: "Conditionals & Reported Speech",
    subtopics: [
      "Zero conditional",
      "First conditional",
      "Second conditional",
      "Third conditional",
      "Mixed conditionals",
      "Reported statements",
      "Reported questions",
      "Reported commands",
      "Backshift of tenses",
      "Reporting verbs",
    ],
  },
  {
    id: "phrasal-prepositions",
    label: "Phrasal Verbs & Prepositions",
    subtopics: [
      "Common Phrasal Verbs",
      "Separable phrasal verbs",
      "Inseparable phrasal verbs",
      "Time prepositions (at/in/on)",
      "Place prepositions (at/in/on)",
      "Movement prepositions",
      "Prepositions after adjectives",
      "Prepositions after verbs",
    ],
  },
  {
    id: "nominal-determiners",
    label: "Nouns, Determiners & Quantifiers",
    subtopics: [
      "Countable vs Uncountable nouns",
      "Plural forms",
      "Genitive (possessive 's)",
      "some / any / no",
      "much / many / a lot of",
      "few / little / a few / a little",
      "all / both / neither / either",
      "each / every",
      "Numerals (cardinal / ordinal)",
      "Noun compounds",
    ],
  },
  {
    id: "pronouns-articles-agreement",
    label: "Pronouns, Articles & Agreement",
    subtopics: [
      "Personal pronouns",
      "Reflexive pronouns",
      "Relative pronouns",
      "Indefinite pronouns",
      "Definite article (the)",
      "Indefinite articles (a/an)",
      "Zero article",
      "Generic reference",
      "Subject-verb agreement",
      "Pronoun-antecedent agreement",
    ],
  },
  {
    id: "adjectives-adverbs-word-order",
    label: "Adjectives, Adverbs & Word Order",
    subtopics: [
      "Adjective order",
      "Comparatives",
      "Superlatives",
      "Adverb placement",
      "Adverbs of frequency",
      "Adverbs of manner",
      "Word order in statements",
      "Word order in questions",
      "Inversion",
    ],
  },
  {
    id: "connectors-structures",
    label: "Connectors & Sentence Structures",
    subtopics: [
      "Coordinating conjunctions",
      "Subordinating conjunctions",
      "Defining relative clauses",
      "Non-defining relative clauses",
      "Adverbial clauses",
      "Noun clauses",
      "Concession (although/despite/in spite of)",
      "Cause & Result",
      "Tag questions",
      "Indirect questions",
      "Exclamatory sentences",
    ],
  },
  {
    id: "punctuation-spelling",
    label: "Punctuation, Spelling & Numerals",
    subtopics: [
      "Comma usage",
      "Apostrophe usage",
      "Capitalization rules",
      "Spelling rules (doubling, -ie/-ei)",
      "Homophones",
      "Numbers written out",
      "Dates and times",
    ],
  },
  {
    id: "vocabulary",
    label: "Vocabulary & Usage",
    subtopics: [
      "Idioms",
      "False Friends / False Cognates",
      "Synonyms & Antonyms",
      "Collocations",
      "Phrasal Verbs in context",
      "Register (formal vs informal)",
      "Word formation (prefixes/suffixes)",
    ],
  },
]
